name: analysis 
channels:
  - conda-forge
dependencies:
  - python=3.8
  # Aesthetics
  - black
  - isort
  - flake8
  # Analysis
  - climpred
  - esmtools
  - regionmask
  - xarray
  - xgcm
  - xrft
  - xskillscore
  # I/O
  - intake-esm
  - h5netcdf
  - netcdf4
  - zarr
  # Miscellaneous 
  - cftime
  - jupyter-server-proxy
  - ipykernel
  - nc-time-axis
  # Numerics
  - bottleneck
  - geopandas
  - numba
  - numpy
  - pandas
  # Parallelization
  - dask
  - dask-jobqueue
  - distributed
  # Regridding
  - esmpy=*=mpi*
  - xesmf
  # Statistics
  - eofs
  - scikit-learn
  - scipy
  - statsmodels
  - xrft
  - xskillscore
  # Workflow
  - jupyter
  - jupyterlab
  - rise
  # Visualization
  - basemap
  - cartopy
  - cmocean
  - descartes
  - geoviews
  - holoviews
  - hvplot
  - matplotlib
  - proplot
  - salem
  - seaborn
  - xhistogram
  - pip
  - pip:
    # Parallelization
    - ncar-jobqueue
