name: analysis 
channels:
  - conda-forge
dependencies:
  - python=3.7
  # Aesthetics
  - black
  - isort
  - flake8
  # Analysis
  - climpred
  - esmlab
  - esmtools
  - xgcm
  # I/O
  - intake-esm
  - h5netcdf
  - netcdf4
  - zarr
  # Miscellaneous 
  - bottleneck
  - cftime
  - jupyter-server-proxy
  - ipykernel
  - nc-time-axis
  # Numerics
  - geopandas
  - numba
  - numpy
  - pandas
  # Parallelization
  - dask
  - dask-jobqueue
  - distributed
  # Regridding
  - esmpy
  - xesmf
  # Statistics
  - eofs
  - scikit-learn
  - scipy
  - statsmodels
  - xrft
  - xskillscore
  # Workflow
  - jupyter
  - jupyterlab
  # Visualization
  - basemap
  - cartopy
  - cmocean
  - geoviews
  - holoviews
  - hvplot
  - matplotlib
  - seaborn
  - xhistogram
  - pip
  - pip:
    # Visualization
    - git+https://github.com/lukelbd/proplot.git
    - salem
    # Analysis
    - esmtools
    - git+https://github.com/NCAR/pop-tools.git
    - xarray>=0.14 # Move to pip to easily force version.
    # Parallelization
    - ncar-jobqueue